# Generated by Django 5.0.4 on 2024-05-02 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruitstore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.CharField(max_length=100)),
                ('product_price', models.PositiveIntegerField()),
                ('product_pic', models.ImageField(upload_to='product_pic/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fruitstore.category')),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
