# Generated by Django 5.0.4 on 2024-05-02 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruitstore', '0002_product_items_delete_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_items',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fruitstore.category'),
        ),
        migrations.AlterField(
            model_name='product_items',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_products', to='fruitstore.category'),
        ),
    ]
