# Generated by Django 5.0.4 on 2024-05-03 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruitstore', '0003_product_items_category_alter_product_items_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_price', models.PositiveIntegerField()),
                ('product_pic', models.ImageField(upload_to='product_pic/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fruitstore.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_products', to='fruitstore.user')),
            ],
        ),
        migrations.DeleteModel(
            name='Product_items',
        ),
    ]
