# Generated by Django 5.0.4 on 2024-05-17 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruitstore', '0004_alter_category_category_name_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Whishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fruitstore.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fruitstore.user')),
            ],
        ),
    ]
